# -*- coding: utf-8 -*-
"""Wave assignments for 124 manual Framework guides."""

from __future__ import annotations

WAVE_SLUGS: dict[int, list[str]] = {
    0: ["beego-go", "fastapi-python", "nestjs-node-typescript"],
    1: ["django-python", "flask-python", "sqlalchemy-python"],
    2: [
        "gin-go",
        "echo-go",
        "fiber-go",
        "chi-go",
        "buffalo-go",
        "goframe-go",
        "gokit-go",
        "gozero-go",
        "gorillamux-go",
        "iris-go",
        "kratos-go",
        "goswagger-go",
        "oapicodegen-go",
        "revel-go",
        "stdlib-go",
    ],
    3: [
        "express-node-typescript",
        "fastify-node-typescript",
        "koa-node-typescript",
        "hono-node-typescript",
        "hapi-node-typescript",
        "restify-node-typescript",
        "elysia-node-typescript",
        "adonisjs-node-typescript",
        "connect-buf-node-typescript",
        "connect-multi-buf-node-typescript",
    ],
    4: [
        "graphql-node-typescript",
        "graphql-federation-node-typescript",
        "grpc-node-typescript",
        "grpcweb-node-typescript",
        "trpc-node-typescript",
        "openapigen-node-typescript",
        "prisma-node-typescript",
        "sequelize-node-typescript",
        "typeorm-node-typescript",
        "drizzle-node-typescript",
        "mikroorm-node-typescript",
    ],
    5: [
        "strapi-node-typescript",
        "payload-node-typescript",
        "keystone-node-typescript",
        "directus-node-typescript",
        "medusa-node-typescript",
        "firebase-functions-node-typescript",
        "supabase-edge-node-typescript",
        "serverless-adapters-node-typescript",
        "apollorouter-node-typescript",
    ],
    6: [
        "actixweb-rust",
        "axum-rust",
        "rocket-rust",
        "warp-rust",
        "http4s-scala",
        "pedestal-clojure",
        "phoenix-elixir",
        "oak-deno-typescript",
        "hanami-ruby",
        "rails-ruby",
    ],
    7: [
        "micronaut-jvm-java",
        "quarkus-jvm-java",
        "play-jvm",
        "springboot-jvm-java",
        "webflux-jvm-java",
        "ktor-jvm-kotlin",
        "vertx-jvm-java",
        "laravel-php",
        "symfony-php",
    ],
    8: [
        "aspnetcore-dotnet",
        "blazor-server-dotnet",
        "blazor-wasm-dotnet",
        "maui-dotnet",
        "fable-dotnet",
    ],
    9: [
        "alpine-vite-typescript",
        "angular-cli-typescript",
        "aurelia-vite-typescript",
        "backbone-vite-typescript",
        "capacitor-vite-typescript",
        "electron-vite-typescript",
        "ember-cli-typescript",
        "expo-react-native-typescript",
        "flutter-dart",
        "htmx-vite-typescript",
    ],
    10: [
        "inferno-vite-typescript",
        "ionic-vite-typescript",
        "kotlin-kmm-mobile",
        "lit-vite-typescript",
        "marko-vite-typescript",
        "million-vite-typescript",
        "mithril-vite-typescript",
        "preact-vite-typescript",
        "qwik-vite-typescript",
        "react-native-web-typescript",
    ],
    11: [
        "react-vite-typescript",
        "riot-vite-typescript",
        "solid-vite-typescript",
        "stencil-compiler-typescript",
        "svelte-vite-typescript",
        "tauri-react-typescript",
        "turbo-vite-typescript",
        "unpoly-vite-typescript",
        "vike-vite-typescript",
        "vue-vite-typescript",
        "webcomponents-vite-typescript",
    ],
    12: ["nextjs-fullstack-typescript", "nuxt-fullstack-typescript"],
    13: [
        "analog-fullstack-typescript",
        "astro-fullstack-typescript",
        "blitz-fullstack-typescript",
        "fresh-fullstack-typescript",
        "gatsby-fullstack-typescript",
        "redwood-fullstack-typescript",
        "remix-fullstack-typescript",
        "shopify-hydrogen-fullstack-typescript",
        "solidstart-fullstack-typescript",
        "sveltekit-fullstack-typescript",
        "tanstack-fullstack-typescript",
        "waku-fullstack-typescript",
    ],
    14: [
        "nx-tooling-typescript",
        "playwright-tooling-typescript",
        "turborepo-tooling-typescript",
        "vitest-tooling-typescript",
    ],
}


def slug_wave(slug: str) -> int | None:
    for wave, slugs in WAVE_SLUGS.items():
        if slug in slugs:
            return wave
    return None
